[project]
name = "subnet-chain"
version = "0.1.0"
description = "Subnet Chain"
requires-python = ">=3.10"
dependencies = [
    "anyio>=4.0",
    "shared",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
